-- ============================================================
-- Migration 000: BetterAuth core tables
-- Generated by reading @better-auth/core/dist/db/get-tables.mjs
-- These are the exact tables BetterAuth's CLI would create for
-- a PostgreSQL database with emailAndPassword + Google + Twitter.
--
-- Apply this FIRST before any other migration.
-- ============================================================

-- ── user ───────────────────────────────────────────────────
-- BetterAuth uses "user" (not "users") as the table name.
-- id is text (not uuid) — all FKs in later migrations must match.

CREATE TABLE IF NOT EXISTS public."user" (
  id              text        PRIMARY KEY,
  name            text        NOT NULL,
  email           text        NOT NULL UNIQUE,
  "emailVerified" boolean     NOT NULL DEFAULT false,
  image           text,
  "createdAt"     timestamptz NOT NULL DEFAULT now(),
  "updatedAt"     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_email_idx ON public."user" (email);

-- ── session ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.session (
  id          text        PRIMARY KEY,
  "expiresAt" timestamptz NOT NULL,
  token       text        NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "ipAddress" text,
  "userAgent" text,
  "userId"    text        NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS session_token_idx  ON public.session (token);
CREATE INDEX IF NOT EXISTS session_userId_idx ON public.session ("userId");

-- ── account ─────────────────────────────────────────────────
-- Stores OAuth provider links (Google, Twitter) and
-- the hashed password for email/password accounts.

CREATE TABLE IF NOT EXISTS public.account (
  id                      text        PRIMARY KEY,
  "accountId"             text        NOT NULL,
  "providerId"            text        NOT NULL,
  "userId"                text        NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  scope                   text,
  password                text,
  "createdAt"             timestamptz NOT NULL DEFAULT now(),
  "updatedAt"             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS account_userId_idx     ON public.account ("userId");
CREATE INDEX IF NOT EXISTS account_providerId_idx ON public.account ("providerId");

-- ── verification ─────────────────────────────────────────────
-- Used for email verification tokens and magic links.

CREATE TABLE IF NOT EXISTS public.verification (
  id           text        PRIMARY KEY,
  identifier   text        NOT NULL,
  value        text        NOT NULL,
  "expiresAt"  timestamptz NOT NULL,
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  "updatedAt"  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS verification_identifier_idx ON public.verification (identifier);
