-- ============================================================================
-- Explore NPM — initial schema
-- Tables for package metadata, weekly download history, taxonomy, user data,
-- and the ingestion-state cursor used by cron jobs.
--
-- Notes:
--   * BetterAuth owns user/session/account/verification tables. We do NOT
--     declare a foreign key to its `user` table because the BetterAuth schema
--     is generated by its own CLI; we only store the user id (text) here.
--   * gen_random_uuid() requires the pgcrypto extension.
--   * Trigram + tsvector indexes power package search.
-- ============================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- ── search-vector helper ──────────────────────────────────────────────────
-- The native `array_to_string(anyarray, text)` is marked STABLE because the
-- generic version dispatches through each element's output function, which
-- can itself be STABLE for some types. Generated columns require strictly
-- IMMUTABLE expressions, so we wrap the call in our own SQL function and
-- assert IMMUTABLE — sound here because both inputs are text and the output
-- of text values is deterministic.
create or replace function package_search_vector(p_description text, p_keywords text[])
returns tsvector
language sql
immutable
parallel safe
as $$
  select to_tsvector(
    'english'::regconfig,
    coalesce(p_description, '') || ' ' || coalesce(array_to_string(p_keywords, ' '), '')
  );
$$;

-- ── packages ───────────────────────────────────────────────────────────────
create table packages (
  id                        uuid primary key default gen_random_uuid(),
  name                      text not null unique,
  scope                     text,
  description               text,
  homepage                  text,
  repository_url            text,
  latest_version            text,
  license                   text,
  author_name               text,
  author_email              text,
  keywords                  text[] not null default '{}',
  dependency_names          text[] not null default '{}',
  first_published_at        timestamptz,
  last_published_at         timestamptz,
  readme_excerpt            text,
  readme_excerpt_updated_at timestamptz,

  -- Hot-path snapshots (updated weekly by recompute-trending cron)
  weekly_downloads          bigint not null default 0,
  rank                      int,
  wow_growth_pct            real,
  is_new_entrant            boolean not null default false,

  -- Generated tsvector for full-text search. Routed through the IMMUTABLE
  -- wrapper above so the generated column is accepted by Postgres.
  search_vector             tsvector
    generated always as (package_search_vector(description, keywords)) stored,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  deleted_at                timestamptz
);

create index packages_rank_idx
  on packages (rank)
  where rank is not null;

create index packages_wow_idx
  on packages (wow_growth_pct desc nulls last);

create index packages_new_entrant_idx
  on packages (is_new_entrant, rank)
  where is_new_entrant;

create index packages_name_trgm
  on packages using gin (name gin_trgm_ops);

create index packages_search_idx on packages using gin (search_vector);

-- ── download_snapshots ─────────────────────────────────────────────────────
create table download_snapshots (
  package_id uuid    not null references packages(id) on delete cascade,
  week_start date    not null,
  downloads  bigint  not null,
  primary key (package_id, week_start)
);

create index download_snapshots_week_idx on download_snapshots (week_start);

-- ── categories ─────────────────────────────────────────────────────────────
create table categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  name        text not null,
  description text,
  parent_id   uuid references categories(id),
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index categories_parent_idx on categories (parent_id) where parent_id is not null;

-- ── package_categories ─────────────────────────────────────────────────────
create table package_categories (
  package_id  uuid not null references packages(id)   on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  confidence  real,
  source      text not null default 'llm',
  assigned_at timestamptz not null default now(),
  primary key (package_id, category_id)
);

create index package_categories_category_idx on package_categories (category_id);

-- ── ingestion_state ────────────────────────────────────────────────────────
-- Singleton row holding the CouchDB _changes cursor and last-run timestamps.
create table ingestion_state (
  id               int primary key default 1,
  changes_since    text,
  last_full_rerank timestamptz,
  last_digest_sent timestamptz,
  constraint ingestion_state_singleton check (id = 1)
);

insert into ingestion_state (id) values (1) on conflict (id) do nothing;

-- ── user_favorites ─────────────────────────────────────────────────────────
-- user_id is BetterAuth's text id; no FK because BetterAuth owns its schema.
create table user_favorites (
  user_id    text not null,
  package_id uuid not null references packages(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, package_id)
);

create index user_favorites_user_idx on user_favorites (user_id);

-- ── user_lists ─────────────────────────────────────────────────────────────
create table user_lists (
  id          uuid primary key default gen_random_uuid(),
  user_id     text not null,
  name        text not null,
  slug        text not null,
  description text,
  is_public   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, slug)
);

create index user_lists_user_idx on user_lists (user_id);
create index user_lists_public_idx on user_lists (is_public) where is_public;

-- ── list_items ─────────────────────────────────────────────────────────────
create table list_items (
  list_id    uuid not null references user_lists(id) on delete cascade,
  package_id uuid not null references packages(id)   on delete cascade,
  position   int,
  notes      text,
  primary key (list_id, package_id)
);

-- ── newsletter_subscriptions ───────────────────────────────────────────────
create table newsletter_subscriptions (
  id              uuid primary key default gen_random_uuid(),
  user_id         text,
  email           text not null unique,
  category_ids    uuid[] not null default '{}',
  verified_at     timestamptz,
  unsubscribed_at timestamptz,
  created_at      timestamptz not null default now()
);

create index newsletter_subscriptions_user_idx
  on newsletter_subscriptions (user_id)
  where user_id is not null;

-- ── updated_at trigger helper ──────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger packages_updated_at
  before update on packages
  for each row execute function set_updated_at();

create trigger categories_updated_at
  before update on categories
  for each row execute function set_updated_at();

create trigger user_lists_updated_at
  before update on user_lists
  for each row execute function set_updated_at();
